
### signup new user
POST http://localhost:3000/auth/signup/
content-type: application/json

{
    "email": "my3@gm.com",
    "password": "1234"
}

### signin an existing user
POST http://localhost:3000/auth/signin/
content-type: application/json

{
    "email": "my3@gm.com",
    "password": "1234"
}

### Whoami
GET http://localhost:3000/auth/whoami


### Signout
GET http://localhost:3000/auth/signout


### Create a new report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Toyota",

    "model": "Heliux",
    
    "year": 2018,
    
    "milage": 55544,

    "lng": 34.235,
    
    "lat": 30.656,
    
    "price": 89000

}



### Find user with specific id
GET http://localhost:3000/auth/1

### Find all users with same email
GET http://localhost:3000/auth/?email=my1@gm.com

### Update a specific user with some of its properties
PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "password": "5678"
}

### Delete a user 
DELETE http://localhost:3000/auth/1