
### signup new user
POST http://localhost:3000/auth/signup/
content-type: application/json

{
    "email": "my11@gm.com",
    "password": "1234"
}

### signin an existing user
POST http://localhost:3000/auth/signin/
content-type: application/json

{
    "email": "my4@gm.com",
    "password": "1234"
}

### Whoami
GET http://localhost:3000/auth/whoami


### Signout
GET http://localhost:3000/auth/signout


### Set approve state
PATCH http://localhost:3000/reports/15
content-type: application/json

{
    "approved": true
}

### Get estimation for query car type
GET http://localhost:3000/reports?make=Ford&model=Mustang&year=1981&lng=45.6&lat=45.2&milage=40000


### Create a new report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Ford",
    "model": "Mustang",
    "year": 1982,
    "milage": 45000,
    "lng": 45.6,
    "lat": 45.2,
    "price": 20000
}



### Find user with specific id
GET http://localhost:3000/auth/1

### Find all users with same email
GET http://localhost:3000/auth/?email=my1@gm.com

### Update a specific user with some of its properties
PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "password": "5678"
}

### Delete a user 
DELETE http://localhost:3000/auth/1